### ISSUE TITLE
Should this repo be archived?

### ISSUE THREAD

**Issue by Aposhian** [LORD-MicroStrain/ROS2_MSCL#4]
Should this repo be archived in favor of the `ros2` branch on https://github.com/LORD-MicroStrain/microstrain_inertial?

**Comment by robbiefish** [comment]
Good point. The readme has been updated to point to the [ros2](https://github.com/LORD-MicroStrain/microstrain_inertial/tree/ros2) branch, and I am going to archive the repo shortly.

I am closing this issue now as I am not sure if I will be able to close it after the repo has been archived
